### ISSUE TITLE
[TUTORIAL] Bisq v2

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university-data#1086]
#### Context
- **Objective**: Completely redo the tutorial on Bisq using only text and screenshots (no videos). If there is sufficient liquidity, it might be better to create it on Bisq v2. Additionally, the original tutorial on Bisq v1 should not be removed imo, but instead, a new clean tutorial named "Bisq v2" should be created.
- **Target audience**: Intermediate to advanced Bitcoiners.
- **Estimated length**: Medium/Long (depending on the level of detail required).

#### Proposed Structure
- A very short theoretical section explaining the importance of P2P exchanges without KYC + a link to the BTC204 course, which elaborates on these theoretical concepts: https://planb.network/courses/btc204;
- A section briefly explaining the theoretical workings of Bisq: what it is, how it works at a high level, and its pros and cons compared to other solutions (Peach, HodlHodl, Robosat...);
- How to install the software;
- How to create and secure your wallet;
- How to buy your first bitcoins;
- How to transfer them to a cold wallet;
- How to sell your bitcoins.

#### Useful Resources
- **Links or documents**: 
	- https://planb.network/tutorials/exchange/bisq
	- https://docs.bisq.network/index.html
	- https://youtu.be/e4-RtLVasmE
	- https://youtu.be/Uw_wD1mN1Tk

#### YAML

```yml
id: 

builder: Bisq

tags:
  - privacy
  - guides

category: peer-to-peer

level: advanced

credits:
  professor: 

# Proofreading metadata

original_language:
proofreading:
  - language: 
    last_contribution_date:
    urgency:
    contributors_id:
      - 
    reward:
```

#### Header (EN)

```markdown
---
name: Bisq v2
description: How to buy and sell bitcoins on Bisq?
---
```
