### ISSUE TITLE
[TUTORIAL] LNP2PBOT

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university-data#1088]
#### Context
- **Objective**: The current tutorial on lnp2pBot is very short. A new, sufficiently detailed version with screenshots at each step is needed. The old tutorial should be removed.
- **Target audience**: Intermediate users
- **Estimated length**: Short/Medium

#### Proposed Structure
- A very short theoretical section explaining the importance of P2P exchanges without KYC + a link to the BTC204 course, which provides more detailed theoretical concepts: https://planb.network/courses/btc204;
- A section briefly explaining the theoretical workings of lnp2pBot: what it is, how it works at a high level, and its pros and cons compared to other solutions (Peach, Bisq, HodlHodl, Robosat...);
- What software to install to get started;
- How to buy your first bitcoins;
- How to sell your bitcoins.

#### Useful Resources
- **Links or documents**: 
	- https://lnp2pbot.com/learn/
	- https://youtu.be/ouZk05HfSnE

#### YAML

```yml
id: 

builder: lnp2pBot

tags:
  - privacy
  - guides

category: peer-to-peer

level: intermediate

credits:
  professor: 

# Proofreading metadata

original_language:
proofreading:
  - language: 
    last_contribution_date:
    urgency:
    contributors_id:
      - 
    reward:
```

#### Header (EN)

```markdown
---
name: lnp2pBot
description: How to buy and sell bitcoins using lnp2pBot?
---
```
