### ISSUE TITLE
[TUTORIAL] Liana

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university-data#1379]
fr.md

```md
---
name: Liana
description: Configurer et utiliser un portefeuille sur Liana
---
```

tutorial.yml

```yaml
id: e40da8c2-7110-4e0e-9fc6-d4d9c35dbbb3

builder: Wizard Sardine

tags:
  - wallets
  - personal-security
  - keys

category: desktop

level: intermediate

credits:
  professor: satoshi-brother

# Proofreading metadata

original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 2025-01-17
    urgency:
    contributors_id:
      - lugaxker
    reward:
```
