### ISSUE TITLE
[TUTORIAL] BTC Map

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university-data#1782]
Assigned to: @Sosylos

Header fr.md : 

```md
---
name: BTC Map
description: Trouvez des endroits où dépenser vos sats
---
```

tutorial.yml : 

```yaml
id: f4691fed-929e-4ffc-87db-f62658f343c6

project_id: d727988b-f3c3-4b52-8ce1-4e9e13a5e503

tags:
  - guides
  - adoption
  - business

category: others

level: beginner

professor_id: fe12ea99-744f-4a00-aef9-36ee1bbacb77

# Proofreading metadata

original_language: fr
proofreading:
  - language: fr
    last_contribution_date: 
    urgency: 1
    contributor_names:
      - Sosylos
    reward: 0
```
