### ISSUE TITLE
First upload of community builders

### ISSUE THREAD

**Issue by Asi0Flammeus** [DecouvreBitcoin/sovereign-university-data#450]
We have now the possibility to discriminate a new type of builders which is `communities`. 
In order to create a more appealing page for this type of builder we have to integrated additionnal information about the community such as location, spoken language, and associated links. 

Now we need to add new communities in the repo by following the below builder.yml file template

```
name: PlanB Network 
category: communities
address_line_1: San Salvador, El Salvador 
address_line_2: Test adress Plan B 
address_line_3: 
language: 
  - en 
  - fr 
  - es 
links: 
  website: https://planb.network 
  twitter: https://twitter.com/planb_network 
  github: https://github.com/DecouvreBitcoin/sovereign-university-data 
  youtube: https://www.youtube.com/@PlanBNetwork 
tags: 
  - education 
  - finance 
```
