### ISSUE TITLE
[TUTORIAL] Lipa Wallet

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university-data#712]
Tutorial requested by Rogzy.

#### Context
- **Objective**: Create a tutorial on how to use the basic features of this Lightning wallet.
- **Target audience**: Beginners
- **Estimated length**: Short

#### Proposed Structure
- Perhaps a theoretical section explaining what Lipa Wallet is, how this solution compares to other Lightning wallets (Phoenix, Zeus, WOS...), and what its advantages and disadvantages are;
- How to create a wallet;
- How to receive bitcoins;
- How to send bitcoins;
- Additional features if necessary, but no need to go into too much detail.

#### Useful Resources
- **Links or documents**: https://lipa.swiss/
- **Inspiring examples**: https://planb.network/fr/tutorials/wallet/blockstream-green

#### YAML

```yml
id: 

builder: Lipa

tags:
  - wallets
  - software
  - lightning

category: mobile

level: beginner

credits:
  professor: 

# Proofreading metadata

original_language:
proofreading:
  - language: 
    last_contribution_date:
    urgency:
    contributors_id:
      - 
    reward:
```

#### Header (EN)

```markdown
---
name: Lipa Wallet
description: How to use Lightning with Lipa Wallet?
---
```
