### ISSUE TITLE
[TUTORIAL] Ubuntu

### ISSUE THREAD

**Issue by LoicPandul** [DecouvreBitcoin/sovereign-university-data#721]
#### Context
- **Objective**: Create a general-purpose tutorial for beginners to understand how to install the Ubuntu OS on their computer and perform some basic tasks.
- **Target audience**: Beginners/intermediate users in computing who are currently using Windows.
- **Estimated length**: Medium

#### Proposed Structure
- Brief theoretical section explaining what an OS is and the existing options;
- Brief theoretical section explaining what Ubuntu is and why it’s an interesting choice;
- Create a bootable USB key (using tools like Balena Etcher...);
- Install and secure the OS;
- Some basic tasks (how to use the browser, how to perform word processing, how to update the system from the terminal, that should suffice for now; further tasks can be covered in future tutorials).
- Closing with a link to another tutorial: https://planb.network/tutorials/others/proton-mail

#### Useful Resources
- **Inspiring examples**: https://planb.network/tutorials/others/linux-mint

#### YAML

```yml
id: 

builder: Canonical

tags:
  - guides
  - software
  - DIY

category: general

level: beginner

credits:
  professor: 

# Proofreading metadata

original_language:
proofreading:
  - language: 
    last_contribution_date:
    urgency:
    contributors_id:
      - 
    reward:
```

#### Header (EN)

```markdown
---
name: Ubuntu
description: Setting up a computer with Ubuntu
---
```
